# Generated by Django 3.2.8 on 2021-10-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='photos/')),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('t', 'Todos'), ('n', 'Novelas'), ('cu', 'Cuentos'), ('cf', 'Ciencia Ficción'), ('r', 'Romance'), ('co', 'Comedia'), ('p', 'Paranormal'), ('f', 'Fantasía'), ('ot', 'Otros')], max_length=15)),
                ('descripcion', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='documentos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
